version: '2'
services:
  kong_vol:
    image: busybox
    volumes:
      - /var/lib/postgresql/data

  kong-database:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes_from:
      - kong_vol

  kong-migration:
    image: kong
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up

  kong:
    image: kong:latest
    depends_on:
      - kong-database
      - kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
    ports:
     - "8000:8000"
     - "8443:8443"
     - "8001:8001"
     - "8444:8444"

